### ISSUE TITLE
Help with ON/OFF with home assistant

### ISSUE THREAD

**Issue by bserrao** [Hypfer/esp8266-midea-dehumidifier#17]
Hey there, 
Could someone help me out... i've added this via MQTT Integration to Home Assistant, and i have 3 entities (Fan, Humidity and WIFI)
On the FAN i have a switch and an option to set the fan speed between (low, medium and high).
When turning on the switch it stays on for 1 or 2s and then off again (No effect on the dehumidifier).
If i turn ON the unit, i can set the fan speed successfuly, but the switch on home assistant shows as turned off (click on it has no effect on the unit).
Any clue why this is happening? 

Here's an example of MQTT info (state) in Home Assistant... When the unit is turned on the "payload: state:" changes to "on".
```
QoS: 0
Payload: state: 'off'
humiditySetpoint: 55
humidityCurrent: 70
errorCode: 0
fanSpeed: low
mode: setpoint
wifi:
  ssid: MY_SSID
  ip: xxx.xxx.xxx.xxx
  rssi: -68
```

Thanks a lot for sharing this projects.
