### ISSUE TITLE
Tank full alert

### ISSUE THREAD

**Issue by elvenpath** [Hypfer/esp8266-midea-dehumidifier#4]
There doesn't seem to be a tank full alert in the firmware. Is it possible to add? Will be quite useful

Thanks

**Comment by Hypfer** [comment]
The issue here is that the "Tank Full" Error is the same as "No Tank at all".
At least as far as my testing goes.

The error code already visible in the JSON published to the MQTT state topic so you can also take a look at that and observe it changing.


I agree that there should be some kind of autoconfigured HA sensor reporting the error state, however personally I'd want it to be reliable.

**Comment by clh27** [comment]
can you point me to where this is in the JSON, please?
I'm going to access the raw MQTT topic here in order to include this into openHAB.
Many thanks!

**Comment by elvenpath** [comment]
I did a search for both "tank" and "full" strings in the ino files and it doesn't seem to be anything related to this. Also can't seem to find anything in the MQTT topics.  Am I doing something wrong?

**Comment by clh27** [comment]
OK, it seems to be in the error code reported in the JSON.
But, what is the error code for tank full / tank missing?
For the dehumidifier device it is the same issue, both shows "P2" on the display.
Is there a list of know error codes available?
Besides this, great job done here!

**Comment by Hypfer** [comment]
@elvenpath 

The error code is read from the state response here:
https://github.com/Hypfer/esp8266-midea-dehumidifier/blob/51d6799d6a0166339e04c2e4e52cbb83cb9e4792/src/esp8266-midea-dehumidifier/serialCommunication.ino#L18

and set to the published mqtt json here:
https://github.com/Hypfer/esp8266-midea-dehumidifier/blob/51d6799d6a0166339e04c2e4e52cbb83cb9e4792/src/esp8266-midea-dehumidifier/esp8266-midea-dehumidifier.ino#L217

with the state topic being declared here:

https://github.com/Hypfer/esp8266-midea-dehumidifier/blob/51d6799d6a0166339e04c2e4e52cbb83cb9e4792/src/esp8266-midea-dehumidifier/esp8266-midea-dehumidifier.ino#L78

@clh27 
> Is there a list of know error codes available?

Unfortunately no. You'd have to figure those out by yourself by testing


I guess it would be possible to introduce something like a errorDescription property for the known values

0 => "no error"
etc.

and then just have a HA sensor which shows that text.

At least that's what Valetudo is doing:

![image](https://user-images.githubusercontent.com/974410/122750892-61ecd780-d28f-11eb-9fdb-e6e8c9f1bf14.png)

**Comment by Syntaxrabbit** [comment]
I just finished by OpenHAB configuration and tested the consequences of removing the water tray while the machine is running.
The error code did not change. Everything else works like a charm.

![grafik](https://user-images.githubusercontent.com/63979422/128413463-d8c6141a-7ee4-4e0e-90cd-21c5cce78f9b.png)

**Comment by Syntaxrabbit** [comment]
New insight: Errorcode für filled tank is **38**.

**Comment by lennvilardi** [comment]
I've rewritten your code parsing the json :
```
mqtt:
  binary_sensor:
    - name: "Tank Full"
      state_topic: "esp8266-midea-dehumidifier/YOURDEHUMIDIFIER/state"
      value_template: "{{ 'ON' if value_json.errorCode == 38 else 'OFF' if value_json.errorCode == 0 else 'OFF' }}"
      payload_on: "ON"
      payload_off: "OFF"
      device_class: problem
      unique_id: yourdehumidifier_tank_full
```
and to add the binary sensor to the device add :

```
    qos: 1
    device:
      identifiers: ["YOURDEHUMIDIFIER"]
      name: "YOURDEHUMIDIFIER"
      manufacturer: "Midea Group Co., Ltd."
      model: "2023.08.0"
```
